### ISSUE TITLE
Request for conversion tool for json files from 3D-FRONT format to SUNCG format

### ISSUE THREAD

**Issue by shinobu-x** [3D-FRONT-FUTURE/3D-FRONT-ToolBox#16]
Thank you for your excellent work. Would it be possible to make conversion tool from 3D-FRONT format to SUNCG format of [house.json](https://github.com/brownvc/deep-synth/blob/master/deep-synth/data/house.py#L42)?

Thank you very much for your help in advance.

**Comment by jwzxgy2007** [comment]
Hi shinobu-x, we will upload conversion tools soon

**Comment by savelovme** [comment]
Hello, I'm also interested in such conversion tool. Are there any news on this issue?

I would very much appreciate your answer.

**Comment by universewill** [comment]
Is there any progress on this? @jwzxgy2007
