### ISSUE TITLE
Penetrating furnitures

### ISSUE THREAD

**Issue by b0ku1** [3D-FRONT-FUTURE/3D-FRONT-ToolBox#4]
While examining the dataset, I discovered that there can be significant overlaps for different furnitures:
![image](https://user-images.githubusercontent.com/12692526/100952183-e67b3280-34c4-11eb-8b6b-4a7c03bbd91d.png)
This is scene: d991e862-ca6b-4dc6-b29b-d6b498e889a9/DiningRoom-12246.

Is there any plan to resolve overlapping furniture like this? Thanks.

**Comment by jwzxgy2007** [comment]
Hi b0ku1, the refined 3D-FRONT dataset and Trescope, a light-weight rendering tool, will be released soon. Please check the website for news,[https://tianchi.aliyun.com/specials/promotion/alibaba-3d-scene-dataset](https://tianchi.aliyun.com/specials/promotion/alibaba-3d-scene-dataset)
thank you!

**Comment by b0ku1** [comment]
thanks. looking forward to it
