### ISSUE TITLE
Rotation encoding

### ISSUE THREAD

**Issue by JOBR0** [3D-FRONT-FUTURE/3D-FRONT-ToolBox#5]
Hi, could you maybe tell me how the rotation of the objects is encoded in the 4 dimensional vector in the JSON-files.
I'm trying to read the files with C++. 

In the json2obj scrpt it is used here:
https://github.com/3D-FRONT-FUTURE/3D-FRONT-ToolBox/blob/0f51d5a3104508e21edfb00a005bed3cbde233d4/scripts/json2obj.py#L127-L134

I'm not sure if the following line is correct. It seems like it should check if the axis has zero length, but instead checks if the sum of all elements is zero. But I can't really tell if I don't know how the rotation is encoded.
https://github.com/3D-FRONT-FUTURE/3D-FRONT-ToolBox/blob/0f51d5a3104508e21edfb00a005bed3cbde233d4/scripts/json2obj.py#L133

I also noticed that there are some hovering and otherwise misplaced objects in the obj files. I'm not sure if this is is related to this or if that's just an error in the dataset.

Thanks!

**Comment by jwzxgy2007** [comment]
Thanks for your feedback! Because for every models in the scene, the rot axis is always (0,x,0), so I use a simple condition to check if the axis is valid.
